# Generated by Django 4.2.1 on 2023-06-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='product',
            field=models.CharField(choices=[('animation_video', 'Animation Video'), ('notes_with_mind_map', 'Notes with mind map'), ('study_notes', 'Study Notes'), ('mcq_package', 'MCQ Package'), ('attendance_tool', 'Attendance Tools'), ('exam_paper_tool', 'Exam Paper Tool'), ('ncert_solution', 'Ncert Solutions')], max_length=200),
        ),
    ]
